### ISSUE TITLE
sampler2DArrayShadow 

### ISSUE THREAD

**Issue by olekristensen** [yasuhirohoshino/ofxPBR#2]
When trying out your dev branch, I get the following error:

`ERROR: 0:289: No matching function for call to textureOffset(sampler2DArrayShadow, vec4, ivec2)
`
Apparently a sampler2D**Array**Shadow is quite achaic, and lacks support.

Would you have any other ideas on how to go about it?

**Comment by yasuhirohoshino** [comment]
I confirmed that error on macOS 10.13.
If you want to use this addon on macOS immediately, pull current dev branch and rename 
'ofxPBR/ofxPBR-example/bin/data/ ofxPBRShaders/pbrFrag_macOS.glsl'
to
'ofxPBR/ofxPBR-example/bin/data/ofxPBRShaders/pbrFrag.glsl',
and try to run example app.
I commented out soft shadow and omni-directional shadow functions in it.

**Comment by yasuhirohoshino** [comment]
Now I fixed some shader bugs on macOS.
Please try out current dev branch.

**Comment by olekristensen** [comment]
hi, thanks - it works brilliantly - skyboxes are upside down though - i think ofImage loads images on the head. is your helper dead, or how much work is it to keep up with the dev branch - really loved to have a persistent material editor in the ofApp.. and could give a hand.

**Comment by yasuhirohoshino** [comment]
sorry, now I fixed the bug about skyboxes upside down.
And I'll start to fix ofxPBRHelper for oF0.10.0 soon.
