### ISSUE TITLE
cubemap roughness artefacts

### ISSUE THREAD

**Issue by olekristensen** [yasuhirohoshino/ofxPBR#4]
Some panoramas produce artifacts when rendered and mipmapped...

it's an issue with the roughness parameter is > 0.0

this is how it looks when rendered
![skaermbillede 2018-09-04 kl 17 05 47](https://user-images.githubusercontent.com/495476/45039946-18428c00-b065-11e8-93dd-38a6d4b35b5c.png)

this is the cached cube map
![screendump of cached](https://user-images.githubusercontent.com/495476/45039994-327c6a00-b065-11e8-9909-781dadeaaaf8.png)

**Comment by yasuhirohoshino** [comment]
I tried to reduce artifact.
Prease check my current commit.

previous version
![previous](https://user-images.githubusercontent.com/9162757/45077911-7df84c00-b129-11e8-93f7-a483a4ea9c06.JPG)

current version
![fixed](https://user-images.githubusercontent.com/9162757/45077912-7e90e280-b129-11e8-86aa-aa1fd13ca147.JPG)

**Comment by olekristensen** [comment]
Hey - thanks for fixing this so quickly 👍 

It looks much better now! I've added animated [stochastic dithering](https://github.com/olekristensen/oresund/blob/16751f9f2852cad34b31efd483fad7cd5b45fc4e/bridge/bin/data/shaders/postEffect/tonemap.frag#L58) to the tonemapping shader and gradients are beautiful in my app now...

<img width="1680" alt="skaermbillede 2018-09-05 kl 10 33 45" src="https://user-images.githubusercontent.com/495476/45081341-4a9cc980-b0f7-11e8-9d44-8324e48a1037.png">
