### ISSUE TITLE
Similar Reflections from another Camera 

### ISSUE THREAD

**Issue by olekristensen** [yasuhirohoshino/ofxPBR#5]
Now, here's a hairy one ...

I am working on projection mapping a space where one wall acts as a 'window' into a much bigger world. The view in this window features a head-tracked camera.

This means that the same model is rendered in two fbos, each with their own camera. 
One is an off-axis view portal camera for the 'window'. The render from this camera is then rendered into a re-render of the model projector's camera (built on mapamok), built on Mapamok.

The illusion is that the mapped scenography objects in the space seem to continue seamlessly through the wall - a sort of interactive trompe l'oeil.

When doing the IBL render i have gotten an unforeseen problem, as the two renders will have different reflection angles. Ideally the reflection angles will all stem from the headtracked camera.

This means I would love to hear from you if you have an idea for how to pass in a second set of matrices that are used to calculate light reflections based on another camera.

I have tried to force both renders to use the head-tracked camera using the ofPBR::setCamera function, but to no avail.  

![ezgif com-optimize](https://user-images.githubusercontent.com/495476/45328654-1ee96b80-b55d-11e8-90a4-c5d884fdca8b.gif)

**Comment by yasuhirohoshino** [comment]
Try to use current commit.
Now rendering scene from multi camera is enable without ofPBR::setCamera before each ofPBR::renderScene.
(Sorry, it was not clear.)

**Comment by olekristensen** [comment]
Hi again, - just checked it out - and yes it is a simpler.

However - I guess my former post was unclear - for multicamera in my example it would be useful to be capable of setting a master camera for light calculation, that can override the automatically loaded matrices explicitly, like you do for shadows, so all renders can use the same eye coordinate for reflection calculations across several camera angles.

In the example above this would make the shading on the bridge element appear continuous, as the fbo render camera should govern lighting on all cameras, to make a seamless render between projection mapped structures and the wall with a view. 

Let me comment a still from the animation above:

<img width="400" alt="skaermbillede 2018-09-11 kl 22 46 05" src="https://user-images.githubusercontent.com/495476/45387290-ec4f7980-b615-11e8-9d1c-67393a488187.png">

**Comment by olekristensen** [comment]
Hi there,

I solved it with this commit:
https://github.com/olekristensen/ofxPBR/commit/a7ca88e79263d34014cc31e36e2a3f09149ff2ca

As it's for my specific use, I am not submitting a PR unless you find it useful

👍
