### ISSUE TITLE
Shadows Not Working on OSX

### ISSUE THREAD

**Issue by NickHardeman** [yasuhirohoshino/ofxPBR#6]
Hello,
Thank you for this wonderful add-on.

Not sure if this is related to [](https://github.com/yasuhirohoshino/ofxPBR/issues/2)
but I don't see any shadows in the example. I made my own project and they don't seem to work there either. I have tried with and without the bin/data/ofxPBRShaders included. 
I don't see any error messages in the console.

I am on OSX 10.13 and OF 0.10

Any help would be greatly appreciated.
Nick

**Comment by NickHardeman** [comment]
I just checked on Windows 10 and OF 0.10.1. It seems that in ofxPBR-example: groundMaterial.metallicMap = &groundMetallic.getTexture(); is causing the issue. It's probably behaving as expected. Since it is shiny, it is reflecting the shadows.

**Comment by moebiussurfing** [comment]
Have you checked ofxPBRHelper? Could be helpful to set shadow easier too

**Comment by digitalcoleman** [comment]
I literally just spent 2 hours trying to solve the same issue...might submit a new example where you turn off the floor material so you can see shadows.
